# Default values for activemq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/pandawms/panda-activemq
  pullPolicy: IfNotPresent
  tag: "latest"

persistentvolume:
  create: true
  class: manual
  path: "/mnt/activemq-data"
  size: 5Gi
  selector: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# accounts
accounts:
  - "panda"
  - "jedi"
  - "idds"
  - "pilot"

# message channels. name:write_accounts,read_account
channels:
  - "iddspanda:idds:panda,jedi"
  - "pandaidds:panda,jedi:idds"
  - "self.jedi_taskstatus:jedi:jedi"
  - "panda_jedi:panda:jedi"
  - "panda_pilot:panda:pilot"
  - "idds.internal:idds:idds"

# base password for active MQ
basePasswd: "ITzqWRCd"

# whether to use secret
secret:
  enabled: false
  name: "msgsvc-dev-secret"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 61613

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
