# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-configmap
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  MARIADB_USER: {{ .Values.database.user }}
  MARIADB_PASSWORD: {{ .Values.database.password }}
  MARIADB_ROOT_PASSWORD: {{ .Values.database.admin_password }}

  {{- if .Values.database.host }}
  IAM_DB_HOST: {{.Values.database.host}}
  {{- else }}
  IAM_DB_HOST: {{ .Release.Name }}-mariadb
  {{- end }}
  IAM_DB_NAME: {{.Values.database.name}}
  IAM_DB_USERNAME: {{.Values.database.user}}
  IAM_DB_PASSWORD: {{.Values.database.password}}

---
# init db
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-initdb
data:
  init_org_db.sql: |-
    CREATE DATABASE {{ .Values.database.name }} CHARACTER SET latin1 COLLATE latin1_swedish_ci;
    GRANT ALL PRIVILEGES on {{ .Values.database.name }}.* to '{{ .Values.database.user }}'@'%' identified by '{{ .Values.database.password }}';

