# Default values for main.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/pandawms/panda-bigmon-core
  pullPolicy: IfNotPresent
  tag: "master"

# start the service when pod gets started
autoStart: true

persistentvolume:
  create: false  
  path: "/mnt/bigmon-main-logs"
  size: 5Gi
  selector: true

hostcerts:
  enabled: false

# http/s proxy if containers need it to access external services
httpsProxy: ""
httpProxy: ""
noProxy: ""

# hostname for external access
hostName: "FIXME"

# secret key for configuration
secretKey: "FIXME"

# Organization
vo: "FIXME"

# deployment
deployment: "POSTGRES"

# debug mode
debugMode: false

# httpd config
httpd:
  # number of WSGI processes
  numWSGI: 10

# database config
database:
  databaseName: panda_db
  port: 5432
  userName: panda
  hostName: "FIXME"
  password: "FIXME"

# rucio
rucio:
  rucioHost: "https://rucio-lb-prod.cern.ch"
  authHost: "https://rucio-auth-prod.cern.ch"
  account: "iddsv1"

# Authentication
auth:
  # list of authentication providers. Possible values are google, cern, github, indigoiam
  providers: []

  # Google OAuth2
  google:
    key: "FIXME"
    secret: "FIXME"

  # CERN
  cern:
    key: "FIXME"
    secret: "FIXME"

  # Github
  github:
    key: "FIXME"
    secret: "FIXME"

  # Indigo IAM
  indigoiam:
    key: "FIXME"
    secret: "FIXME"
    # base URL of IAM. e.g. https://panda-iam-doma.cern.ch
    basePath: "FIXME"

# cric
cric:
  apiUrl: "https://datalake-cric.cern.ch/api/atlas/pandaqueue/query/?json"

# iDDS
idds:
  host: 'https://idds-rest:443/idds'

# AWS
aws:
  accessKey: "FIXME"
  secretKey: "FIXME"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  httpsPort: 443

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'optional'
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - domain: cern.ch
      hostOverride: ""
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: ""
      hosts:
        - domain: cern.ch
          hostOverride: ""
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

route:
  enabled: false

  ### configuration for OKD
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
