# Default values for iam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


database:
  name: &db_name iamdb
  user: &db_user iam
  password: &db_password MyPandaPass0508
  admin_password: &db_admin_password MyAdminPass0508

organization: &organization Rubin
secret_enabled: &secret_enabled false

main:
  enabled: true

  secret:
    enabled: *secret_enabled
    name: "iam-dev-secret"

  iam:
    organization: *organization
    cilogon_client_id: "FIXME"
    cilogon_client_secret: "FIXME"

  database:
    name: *db_name
    user: *db_user
    password: *db_password

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-iam-dev.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            hostOverride: panda-iam-dev.cern.ch

mariadb:
  enabled: true

  iam:
    organization: *organization

  database:
    name: *db_name
    user: *db_user
    password: *db_password
    admin_password: *db_admin_password

  secret:
    enabled: *secret_enabled
    name: "iam-dev-secret"
